# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 92635f6f4ac5a6eb3d1232497f683e50b513cedd80a5ea48a8d9035d614d9cfaaf6c61d93f2f218b491ff900e032032eca9eff69f84c347d73bb8528a6177f2f

test:
  secret_key_base: 31a83ef5e3ed02331a1ec72b27169c59fb2953402b9c5b3b83d6eec671d4609fc413a558a30925bc1329698d1231a342a60f5e41686eea2b8c95ff8d6c8dbba9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
